/**
 * 장비 sprite id → 이미지. RN은 require()를 정적으로만 분석하기 때문에
 * (동적 경로 조합 불가) 새 이미지를 넣을 때마다 여기 한 줄씩 추가해야 한다.
 * 아직 없는 sprite는 그냥 빠뜨려두면 된다 — 쓰는 쪽에서 undefined를 아이콘 없음으로 처리한다.
 */
export const itemIcons: Partial<Record<string, number>> = {
  sword_1: require('@/assets/images/items/sword_1.png'),
  sword_2: require('@/assets/images/items/sword_2.png'),
  sword_3: require('@/assets/images/items/sword_3.png'),
  sword_4: require('@/assets/images/items/sword_4.png'),
  sword_5: require('@/assets/images/items/sword_5.png'),
  sword_6: require('@/assets/images/items/sword_6.png'),
  sword_7: require('@/assets/images/items/sword_7.png'),
  sword_8: require('@/assets/images/items/sword_8.png'),
  sword_9: require('@/assets/images/items/sword_9.png'),
  sword_10: require('@/assets/images/items/sword_10.png'),
  helm_1: require('@/assets/images/items/helm_1.png'),
  helm_2: require('@/assets/images/items/helm_2.png'),
  helm_3: require('@/assets/images/items/helm_3.png'),
  helm_4: require('@/assets/images/items/helm_4.png'),
  helm_5: require('@/assets/images/items/helm_5.png'),
  helm_6: require('@/assets/images/items/helm_6.png'),
  helm_7: require('@/assets/images/items/helm_7.png'),
  helm_8: require('@/assets/images/items/helm_8.png'),
  helm_9: require('@/assets/images/items/helm_9.png'),
  helm_10: require('@/assets/images/items/helm_10.png'),
  armor_1: require('@/assets/images/items/armor_1.png'),
  armor_2: require('@/assets/images/items/armor_2.png'),
  armor_3: require('@/assets/images/items/armor_3.png'),
  armor_4: require('@/assets/images/items/armor_4.png'),
  armor_5: require('@/assets/images/items/armor_5.png'),
  armor_6: require('@/assets/images/items/armor_6.png'),
  armor_7: require('@/assets/images/items/armor_7.png'),
  armor_8: require('@/assets/images/items/armor_8.png'),
  armor_9: require('@/assets/images/items/armor_9.png'),
  armor_10: require('@/assets/images/items/armor_10.png'),
  gloves_1: require('@/assets/images/items/gloves_1.png'),
  gloves_2: require('@/assets/images/items/gloves_2.png'),
  gloves_3: require('@/assets/images/items/gloves_3.png'),
  gloves_4: require('@/assets/images/items/gloves_4.png'),
  gloves_5: require('@/assets/images/items/gloves_5.png'),
  gloves_6: require('@/assets/images/items/gloves_6.png'),
  gloves_7: require('@/assets/images/items/gloves_7.png'),
  gloves_8: require('@/assets/images/items/gloves_8.png'),
  gloves_9: require('@/assets/images/items/gloves_9.png'),
  gloves_10: require('@/assets/images/items/gloves_10.png'),
  boots_1: require('@/assets/images/items/boots_1.png'),
  boots_2: require('@/assets/images/items/boots_2.png'),
  boots_3: require('@/assets/images/items/boots_3.png'),
  boots_4: require('@/assets/images/items/boots_4.png'),
  boots_5: require('@/assets/images/items/boots_5.png'),
  boots_6: require('@/assets/images/items/boots_6.png'),
  boots_7: require('@/assets/images/items/boots_7.png'),
  boots_8: require('@/assets/images/items/boots_8.png'),
  boots_9: require('@/assets/images/items/boots_9.png'),
  boots_10: require('@/assets/images/items/boots_10.png'),
  accessory_1: require('@/assets/images/items/accessory_1.png'),
  accessory_2: require('@/assets/images/items/accessory_2.png'),
  accessory_3: require('@/assets/images/items/accessory_3.png'),
  accessory_4: require('@/assets/images/items/accessory_4.png'),
  accessory_5: require('@/assets/images/items/accessory_5.png'),
  accessory_6: require('@/assets/images/items/accessory_6.png'),
  accessory_7: require('@/assets/images/items/accessory_7.png'),
  accessory_8: require('@/assets/images/items/accessory_8.png'),
  accessory_9: require('@/assets/images/items/accessory_9.png'),
  accessory_10: require('@/assets/images/items/accessory_10.png'),
};
